#[derive(Clone, Copy)]
pub enum ShellKind {
    Bash,
    Zsh,
}

impl From<crate::Shell> for ShellKind {
    fn from(s: crate::Shell) -> Self {
        match s {
            crate::Shell::Bash => ShellKind::Bash,
            crate::Shell::Zsh => ShellKind::Zsh,
        }
    }
}

/// Hook code for `eval "$(rat shell-init bash)"`. Reports each finished
/// command via `rat emit-shell`, detached and fail-silent — a dead daemon
/// must never slow the shell down.
pub fn snippet(shell: ShellKind) -> anyhow::Result<String> {
    let rat = std::env::current_exe()?;
    let rat = rat.display();
    Ok(match shell {
        ShellKind::Bash => format!(
            r#"# RATO shell hooks (bash) — generated by `rat shell-init bash`
_rat_bin="{rat}"
_rat_now_ms() {{ date +%s%3N; }}
_rat_preexec() {{
  [ -n "$COMP_LINE" ] && return
  [ -n "$_rat_cmd" ] && return
  case "$BASH_COMMAND" in _rat_*|"$PROMPT_COMMAND") return;; esac
  _rat_cmd=$BASH_COMMAND
  _rat_start=$(_rat_now_ms)
}}
_rat_precmd() {{
  local _rat_exit=$?
  if [ -n "$_rat_cmd" ]; then
    local _rat_dur=$(( $(_rat_now_ms) - _rat_start ))
    ( "$_rat_bin" emit-shell --cmd "$_rat_cmd" --cwd "$PWD" --exit "$_rat_exit" --duration-ms "$_rat_dur" >/dev/null 2>&1 & )
    _rat_cmd=
  fi
}}
trap '_rat_preexec' DEBUG
PROMPT_COMMAND="_rat_precmd${{PROMPT_COMMAND:+;$PROMPT_COMMAND}}"
"#
        ),
        ShellKind::Zsh => format!(
            r#"# RATO shell hooks (zsh) — generated by `rat shell-init zsh`
_rat_bin="{rat}"
zmodload zsh/datetime 2>/dev/null
_rat_preexec() {{
  _rat_cmd=$1
  _rat_start=$(( EPOCHREALTIME * 1000 ))
}}
_rat_precmd() {{
  local _rat_exit=$?
  if [ -n "$_rat_cmd" ]; then
    local _rat_dur=$(( EPOCHREALTIME * 1000 - _rat_start ))
    ( "$_rat_bin" emit-shell --cmd "$_rat_cmd" --cwd "$PWD" --exit "$_rat_exit" --duration-ms "${{_rat_dur%.*}}" >/dev/null 2>&1 & )
    _rat_cmd=
  fi
}}
autoload -Uz add-zsh-hook
add-zsh-hook preexec _rat_preexec
add-zsh-hook precmd _rat_precmd
"#
        ),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippets_contain_shell_specific_hooks() {
        let bash = snippet(ShellKind::Bash).unwrap();
        let zsh = snippet(ShellKind::Zsh).unwrap();

        assert!(bash.contains("# RATO shell hooks (bash)"));
        assert!(bash.contains("trap '_rat_preexec' DEBUG"));
        assert!(bash.contains("PROMPT_COMMAND=\"_rat_precmd"));
        assert!(zsh.contains("# RATO shell hooks (zsh)"));
        assert!(zsh.contains("autoload -Uz add-zsh-hook"));
        assert!(zsh.contains("add-zsh-hook preexec _rat_preexec"));
        assert!(zsh.contains("add-zsh-hook precmd _rat_precmd"));
        assert_ne!(bash, zsh);
    }

    #[test]
    fn shell_converts_to_matching_kind() {
        assert!(matches!(
            ShellKind::from(crate::Shell::Bash),
            ShellKind::Bash
        ));
        assert!(matches!(ShellKind::from(crate::Shell::Zsh), ShellKind::Zsh));
    }
}
